--liquibase formatted sql

--changeset liquibase:1
CREATE TABLE IF NOT EXISTS category
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    created timestamp,
    name varchar(255),
    updated timestamp
);