--liquibase formatted sql

--changeset liquibase:4
CREATE TABLE IF NOT EXISTS comment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar(255),
    email varchar(255),
    text varchar(255),
    index smallint,

    created timestamp,
    updated timestamp,

    product_id bigint,
    FOREIGN KEY (product_id)
      REFERENCES product(id)
);
