--liquibase formatted sql

--changeset liquibase:5
CREATE TABLE IF NOT EXISTS user_
(
    id          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255),
    created     timestamp,
    updated     timestamp
);