--liquibase formatted sql

--changeset liquibase:8
CREATE TABLE IF NOT EXISTS order_line_item
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    quantity bigint,

    product_id bigint,
    order_id uuid,
    FOREIGN KEY (order_id) REFERENCES order_(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
    );