--liquibase formatted sql

--changeset liquibase:9
CREATE TABLE IF NOT EXISTS message
(
    id          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       varchar(255),
    text        varchar(255),
    city        varchar(255),
    email       varchar(255),
    created     timestamp,
    updated     timestamp
);