

CREATE TABLE IF NOT EXISTS product_category
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    created timestamp,
    name varchar(255),
    updated timestamp
);

CREATE TABLE IF NOT EXISTS product
(
    id          bigint NOT NULL PRIMARY KEY,
    created     timestamp,
    description varchar(255),
    price       numeric(19, 2),
    title       varchar(255),
    updated     timestamp,
    category_id bigint,
    FOREIGN KEY (category_id)
        REFERENCES product_category (id)
);